var prompts=['Choose a theme:','Choose a header:', 'Chose a body:', 'Chose a footer','On the next page, press CTRL+A then CTRL+C to copy the generated email'];
var choices=[['Dark', 'Light'],['img/header1.png','img/header2.png'],['img/body1.png','img/body2.png'],['img/footer1.png','img/footer2.png'],['data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxNi4yLjEsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DQo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KCSB3aWR0aD0iNTEycHgiIGhlaWdodD0iNTEycHgiIHZpZXdCb3g9IjAgMCA1MTIgNTEyIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCA1MTIgNTEyOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+DQo8cG9seWdvbiBwb2ludHM9IjE2MCwxMTUuNCAxODAuNyw5NiAzNTIsMjU2IDE4MC43LDQxNiAxNjAsMzk2LjcgMzEwLjUsMjU2ICIvPg0KPC9zdmc+DQo=','http://1x1px.me/FFFFFF-0.png']]
var html=[
	['<tr><td align="center" valign="top"><!-- BEGIN PREHEADER // --><table border="0" cellpadding="0" cellspacing="0" width="100%" id="templatePreheader"><tr><td valign="top" class="preheaderContent" style="padding-top:10px; padding-right:20px; padding-bottom:10px; padding-left:20px;">Short Teaser to be shown to users. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet</td><!-- *|IFNOT:ARCHIVE_PAGE|* --><td valign="top" width="180" class="preheaderContent" style="padding-top:10px; padding-right:20px; padding-bottom:10px; padding-left:0;">Email not displaying correctly?<br /><a href="#" target="_blank">View it in your browser</a>.</td><!-- *|END:IF|* --></tr></table><!-- // END PREHEADER --></td></tr><tr><td align="center" valign="top"><!-- BEGIN HEADER // --><table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateHeader"><tr><td valign="top" class="headerContent"><img src="https://placehold.it/600x150" id="headerImage" /></td></tr></table><!-- // END HEADER --></td></tr>',
	'<tr><td align="center" valign="top"><!-- BEGIN PREHEADER // --><table border="0" cellpadding="0" cellspacing="0" width="100%" id="templatePreheader"><tr><td valign="top" class="preheaderContent" style="padding-top:10px; padding-right:20px; padding-bottom:10px; padding-left:20px;"><img src="https://placehold.it/150x50" style=""></td><td valign="top" class="preheaderContent" width="200px;" style="text-align:right;padding-top:15px; padding-bottom:10px; padding-right:20px;"><p>Email not displaying correctly?</p> <p><a href="">View it in your browser</a>.</p></td><!-- *|END:IF|* --></tr></table><!-- // END PREHEADER --></td></tr><tr><td align="center" valign="top"><!-- BEGIN HEADER // --><table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateHeader"><tr><td valign="top" class="headerContent"><h2 style="line-height:125%;">Lorem ipsum dolor sit amet, ornare maecenas et eu varius, vulputate ut, volutpat vehicula.</h2></td></tr></table><!-- // END HEADER --></td></tr>'],
	['<tr><td align="center" valign="top"><table border="0" cellspacing="0" width="100%" id="templateBody"><tr><td valign="top" class="bodyContent"><h1>Titre</h1><h3>Sous-titre. Mettre texte ici.</h3><p> Lorem ipsum dolor sit amet, ornare maecenas et eu varius, vulputate ut, volutpat vehicula. Morbi nibh mi lectus. Ipsum conubia amet, vestibulum molestie urna lacus sed fermentum, mattis sapien, nulla fusce odio magna urna sit, diam donec nam lobortis consectetuer viverra.</p><p>At viverra integer. Morbi odio suscipit rutrum, libero facilisis neque magna eros enim. Cras fringilla. Imperdiet massa non erat non cum, pellentesque sed ac fermentum nisl. Nulla sit ut volutpat morbi elit consectetuer, ultricies tortor mus lacus ut quis in, augue pede eget congue mus pellentesque elit, wisi erat integer, augue id in inceptos vulputate.</p></br><p>Yours Truely,</p><p>Jane Doe.</p></td></tr></table></td></tr>',
	'<tr><td align="center" valign="top"><!-- BEGIN COLUMNS // --><table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateColumns"><tr><td align="center" valign="top" class="templateColumnContainer" style="padding-top:20px;"><table border="0" cellpadding="20" cellspacing="0" width="100%"><tr><td class="leftColumnContent"><img src="https://placehold.it/260x200" style="max-width:260px;" class="columnImage" /></td></tr><tr><td valign="top" class="leftColumnContent"><h2 style="text-align:center;margin-top:-20px;padding-bottom:10px;">Block Item</h2><h4 style="text-align:center;">Lorem ipsum dolor sit amet, ornare maecenas et eu varius, vulputate ut, volutpat vehicula. Morbi nibh mi lectus. Ipsum conubia amet</h4></td></tr></table></td><td align="center" valign="top" class="templateColumnContainer" style="padding-top:20px;"><table border="0" cellpadding="20" cellspacing="0" width="100%"><tr><td class="rightColumnContent"><img src="https://placehold.it/260x200" style="max-width:260px;" class="columnImage" /></td></tr><tr><td valign="top" class="rightColumnContent"><h2 style="text-align:center;margin-top:-20px;padding-bottom:10px;">Block Item</h2><h4 style="text-align:center;">Lorem ipsum dolor sit amet, ornare maecenas et eu varius, vulputate ut, volutpat vehicula. Morbi nibh mi lectus. Ipsum conubia amet</h4></td></tr></table></td></tr></table><!-- // END COLUMNS --></td></tr>'],
	['<tr><td align="center" valign="top"><table border="0" cellspacing="0" width="100%" id="templateFooter"><tr><td class="footerContent"><div style="width:100%;text-align:center;"><a href="#"><img src="https://ci3.googleusercontent.com/proxy/aUicCc4NdusQfi3ux5w1xc_W5e2R1HlMYstS_aQ6liVbRB1TsgAB-l5_yEJEEHWCqZMbVyii12gDJNbCk0JzfpWZqlHTHVFN3HGXHnzC-hvcyM7HERXEs8kEBmbORdW2fA=s0-d-e1-ft#https://dt5zaw6a98blc.cloudfront.net/site-static/images/footer/facebook.png"></a><a href="#"><img src="https://ci4.googleusercontent.com/proxy/pOgcjuE-Bq2LalyOyNZogZPg2IEQVKC7MGIONZZPy_R7mrdK1THvWtLYGPcBvRH3SdjV4jF4qRa8UwCwfsWMhU-d4rZ-AaANg_lMTsL2-nIV019B-ZhywO8_GFm-wD9b=s0-d-e1-ft#https://dt5zaw6a98blc.cloudfront.net/site-static/images/footer/twitter.png"></a></span></br><p style="text-align:center;">Oportunity to <a href="#">unsubscribe</a>.</p><p style="text-align:center;">Copyright (c) 2015 Joshua Draxten | 123 Nth Avenue, Starling City, Mn 31415 USA</p></td></tr></table></td>',
	'<tr><td align="center" valign="top"><table border="0" cellspacing="0" width="100%" id="templateFooter"><tr><td class="footerContent"><div style="width:100%;text-align:right;"><img src="http://placehold.it/125x125" style="border-radius:100%;"></div></td><td class="footerContent"><div style="width:100%;text-align:left;"><h1>Jane Doe</h1><h3>Director of Finance</h3><a href="#"><img src="https://ci3.googleusercontent.com/proxy/aUicCc4NdusQfi3ux5w1xc_W5e2R1HlMYstS_aQ6liVbRB1TsgAB-l5_yEJEEHWCqZMbVyii12gDJNbCk0JzfpWZqlHTHVFN3HGXHnzC-hvcyM7HERXEs8kEBmbORdW2fA=s0-d-e1-ft#https://dt5zaw6a98blc.cloudfront.net/site-static/images/footer/facebook.png"></a><a href="#"><img src="https://ci4.googleusercontent.com/proxy/pOgcjuE-Bq2LalyOyNZogZPg2IEQVKC7MGIONZZPy_R7mrdK1THvWtLYGPcBvRH3SdjV4jF4qRa8UwCwfsWMhU-d4rZ-AaANg_lMTsL2-nIV019B-ZhywO8_GFm-wD9b=s0-d-e1-ft#https://dt5zaw6a98blc.cloudfront.net/site-static/images/footer/twitter.png"></a></span></td></tr></table></td></tr><tr><td align="center" valign="top"><table cellpadding="0px" border="0px" width:"100%"><tr><td class="footerContent"><br><p style="text-align:center;">Opportunity to <a href="#">unsubscribe</a>.</p><p style="text-align:center;">Copyright (c) 2015 Joshua Draxten | 123 Nth Avenue, Starling City, Mn 31415 USA</p></td></tr></table></td></tr>']];

var css=[
	['#templatePreheader{background-color:#f3f3f3;border-bottom:1px solid #f3f3f3;}.preheaderContent{color:#808080;font-family:Helvetica;font-size:10px;line-height:125%;text-align:left;}.preheaderContent a:link, .preheaderContent a:visited, /* Yahoo! Mail Override */ .preheaderContent a .yshortcuts /* Yahoo! Mail Override */{color:#606060;font-weight:normal;text-decoration:underline;}#templateHeader{background-color:#bdc3c7;margin:-8px;}#headerImage{height:auto;max-width:600px;}',
	'#templatePreheader{background-color:#444;border-bottom:1px solid #CCCCCC;}.preheaderContent{color:#808080;font-family:Helvetica;font-size:10px;line-height:125%;text-align:left;}.preheaderContent a:link, .preheaderContent a:visited, /* Yahoo! Mail Override */ .preheaderContent a .yshortcuts /* Yahoo! Mail Override */{color:#606060;font-weight:normal;text-decoration:underline;}#templateHeader{background-color:#bdc3c7;margin:-8px;}#headerImage{height:auto;max-width:600px;}.headerContent{padding-left: 20px;padding-right: 20px;padding-top: 20px;padding-bottom: 20px;}'],
	['.bodyContent{color:#505050;font-family:Helvetica;font-size:16px;line-height:150%;padding-top:20px;padding-right:20px;padding-bottom:20px;padding-left:20px;text-align:left;}.bodyContent a:link, .bodyContent a:visited, /* Yahoo! Mail Override */ .bodyContent a .yshortcuts /* Yahoo! Mail Override */{color:#EB4102;font-weight:normal;text-decoration:underline;}',
	'.bodyContent{color:#505050;font-family:Helvetica;font-size:16px;line-height:150%;padding-top:20px;padding-right:20px;padding-bottom:20px;padding-left:20px;text-align:left;}.bodyContent a:link, .bodyContent a:visited, /* Yahoo! Mail Override */ .bodyContent a .yshortcuts /* Yahoo! Mail Override */{color:#EB4102;font-weight:normal;text-decoration:underline;}'],
	['.footerContent{color:#808080;padding-top:20px;font-size: 10px;font-family: Helvetica;padding-right:20px;padding-bottom:20px;padding-left:20px;}',
	'.footerContent{color:#808080;padding-top:20px;font-size: 10px;font-family: Helvetica;padding-right:20px;padding-bottom:20px;padding-left:20px;}']];

var html_output = '';
var css_output  = 'h1{color:#202020 !important;display:block;font-family:Helvetica;font-size:26px;font-style:normal;font-weight:bold;line-height:100%;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:10px;margin-left:0;text-align:left;}h2{color:#404040 !important;display:block;font-family:Helvetica;font-size:20px;font-style:normal;font-weight:bold;line-height:100%;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:10px;margin-left:0;text-align:left;}h3{color:#606060 !important;display:block;font-family:Helvetica;font-size:16px;font-style:italic;font-weight:normal;line-height:100%;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:10px;margin-left:0;text-align:left;}h4{color:#808080 !important;display:block;font-family:Helvetica;font-size:14px;font-style:italic;font-weight:normal;line-height:100%;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:10px;margin-left:0;text-align:left;}';

var n = 0;
function nextChoice(choice){
	$("#choice-container").animate({
		opacity:0
	},1000, function(){
		n++;
		if(choice==0||choice==1){
			html_output+=html[n-2][choice];
			css_output += css[n-2][choice];
		};
		if (n<4){
			$('#progress>span:nth-of-type('+n+')').css({color:"#2980b9"});
			$('#choiceName').text(prompts[n]);
			document.getElementById('choice').innerHTML='<td><a href="javascript:void(0);" onclick="nextChoice(0);"><img class="choiceImage" src="'+choices[n][0]+'"></a><hr>'+
								 					    '<a href="javascript:void(0);" onclick="nextChoice(1);"><img class="choiceImage" src="'+choices[n][1]+'"></a></td>';
			
		} else {
			document.write('<body style="background-color:#f1eae0;"><style>'+css_output+'</style><table width="100%" border="0" cellspacing="0" cellpadding="0"><tr><td width="600px" align="center"><table style="width:600px;background-color:#f3f3f3;">'+html_output+'</table></td></tr></table></body>')
		}
	});
	$("#choice-container").animate({opacity:1},1000);
}